-- ==========================================================================
-- SCRIPT DE CONFIGURACIÓN DE BASE DE DATOS PARA SUPABASE (VAPEX)
-- Ejecuta este script en el editor SQL de Supabase para crear las tablas
-- e insertar los productos iniciales.
-- ==========================================================================

-- 1. Crear tabla de productos
CREATE TABLE IF NOT EXISTS public.products (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    brand TEXT NOT NULL,
    category TEXT NOT NULL,
    price NUMERIC(10, 2) NOT NULL,
    rating NUMERIC(3, 1) NOT NULL DEFAULT 5.0,
    reviews INTEGER NOT NULL DEFAULT 0,
    image TEXT NOT NULL,
    in_stock BOOLEAN NOT NULL DEFAULT TRUE,
    stock_count INTEGER NOT NULL DEFAULT 10,
    description TEXT NOT NULL,
    details JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- 2. Habilitar Seguridad de Nivel de Fila (RLS)
ALTER TABLE public.products ENABLE ROW LEVEL SECURITY;

-- 3. Crear Políticas de RLS
-- Política 1: Permitir lectura pública a cualquiera (incluso no autenticados)
DROP POLICY IF EXISTS "Permitir lectura publica" ON public.products;
CREATE POLICY "Permitir lectura publica" 
ON public.products 
FOR SELECT 
USING (true);

-- Política 2: Permitir inserción, actualización y borrado solo a usuarios autenticados
DROP POLICY IF EXISTS "Permitir escrituras a usuarios autenticados" ON public.products;
CREATE POLICY "Permitir escrituras a usuarios autenticados" 
ON public.products 
FOR ALL 
TO authenticated
USING (true)
WITH CHECK (true);

-- 4. Truncar tabla de productos para asegurar semilla limpia
TRUNCATE TABLE public.products RESTART IDENTITY CASCADE;

-- 5. Insertar Datos de Ejemplo (Semilla)
INSERT INTO public.products (name, brand, category, price, rating, reviews, image, in_stock, stock_count, description, details)
VALUES 
(
  'Mango Peach Fusion Disposable', 
  'VAPEX Neon', 
  'vapers', 
  12.99, 
  4.8, 
  142, 
  '/images/vape_mango_peach.png', 
  TRUE, 
  15, 
  'Experimenta la explosión tropical definitiva con la fusión dulce de mangos maduros y melocotón jugoso. Este vape desechable ofrece caladas ultra suaves con un golpe de sabor consistente de principio a fin.',
  '{"puffs": "8000 Caladas", "nicotine": [0, 10, 20], "flavor": "Mango, Melocotón y Toque Ice", "battery": "650mAh (Recargable USB-C)", "capacity": "14ml"}'::jsonb
),
(
  'Pod Kit CyberBlue Pro', 
  'AeroPod', 
  'vapers', 
  29.99, 
  4.9, 
  88, 
  '/images/vape_pod_kit.png', 
  TRUE, 
  8, 
  'El Pod Kit definitivo para el día a día. Fabricado con aleación de aluminio aeroespacial y fibra de carbono. Cuenta con activación por calada o botón, control de flujo de aire ajustable y una pantalla inteligente OLED para el control de potencia.',
  '{"puffs": "N/A (Recargable)", "nicotine": [0, 10, 20, 50], "flavor": "Compatible con sales y e-liquids", "battery": "1000mAh (Carga Rápida USB-C)", "capacity": "2ml (Cartucho magnético)"}'::jsonb
),
(
  'Premium E-Liquid Fresa Limón', 
  'Juice Labs', 
  'vapers', 
  15.99, 
  4.7, 
  210, 
  '/images/vape_eliquid_bottle.png', 
  TRUE, 
  25, 
  'Una mezcla magistral de fresas dulces recién cosechadas equilibradas con un toque cítrico y refrescante de limón ácido. Ideal para vapear todo el día en atomizadores sub-ohm.',
  '{"puffs": "N/A", "nicotine": [0, 3, 6], "flavor": "Fresa Madura y Limonada Ácida", "battery": "N/A", "capacity": "60ml (70VG / 30PG)"}'::jsonb
),
(
  'Mod Box Cyberpunk Gold 200W', 
  'VoltTech', 
  'vapers', 
  64.99, 
  5.0, 
  45, 
  '/images/vape_mod_cyber.png', 
  TRUE, 
  4, 
  'Para los entusiastas del vapeo y el cloud chasing. Mod electrónico de doble batería 18650 con una potencia máxima de 200W. Diseño ergonómico de fibra de carbono con detalles chapados en oro y chipset de última generación con modos bypass y control de temperatura.',
  '{"puffs": "N/A", "nicotine": [0], "flavor": "N/A", "battery": "Doble Batería 18650 (No incluidas)", "capacity": "Rosca 510 universal"}'::jsonb
),
(
  'Cargadores de N2O Premium (50 uds)', 
  'CreamMaster Import', 
  'reposteria', 
  24.99, 
  4.8, 
  112, 
  '/images/n2o_charger.png', 
  TRUE, 
  30, 
  'Cargadores de óxido nitroso (N2O) de calidad culinaria para sifones de nata y espumas gourmet. Fabricados en acero reciclable de alta resistencia, garantizando la pureza del gas para repostería profesional sin residuos de aceite.',
  '{"puffs": "N/A", "nicotine": [0], "flavor": "Grado Alimentario Certificado E942", "battery": "N/A", "capacity": "50 cápsulas (8g N2O c/u)"}'::jsonb
),
(
  'Bombona de Óxido Nitroso N2O 640g', 
  'GourmetWhip', 
  'reposteria', 
  39.99, 
  4.9, 
  64, 
  '/images/n2o_charger.png', 
  TRUE, 
  12, 
  'Cilindro de gas óxido nitroso (N2O) de 640g de importación exclusiva para hostelería y repostería gourmet. Ahorra tiempo en recargas en comparación con los cargadores individuales. Compatible con la mayoría de sifones mediante regulador.',
  '{"puffs": "N/A", "nicotine": [0], "flavor": "Pureza 99.9% Alimentaria", "battery": "N/A", "capacity": "640g de gas neto"}'::jsonb
),
(
  'Encendedor Zippo Edición Dragón', 
  'Zippo Collectibles', 
  'coleccionismo', 
  89.99, 
  5.0, 
  28, 
  '/images/collectible_dragon.png', 
  TRUE, 
  5, 
  'Encendedor a prueba de viento de edición limitada, importado directamente desde USA. Acabado en latón cepillado de gran grosor con un intrincado grabado en relieve de un dragón oriental tradicional. Viene en estuche de regalo de lujo.',
  '{"puffs": "N/A", "nicotine": [0], "flavor": "Latón Cepillado Grabado", "battery": "Mecanismo de Piedra y Mecha", "capacity": "Estuche Oficial Incluido"}'::jsonb
),
(
  'Cenicero de Cristal de Murano Vintage', 
  'Murano Art', 
  'coleccionismo', 
  120.00, 
  4.7, 
  15, 
  '/images/vape_mod_cyber.png', 
  TRUE, 
  2, 
  'Pieza de colección vintage de los años 70, importada de Venecia, Italia. Cenicero soplado a mano en cristal de Murano con inclusiones de pan de oro y espirales de colores vibrantes. Un toque único y elegante de exclusividad.',
  '{"puffs": "N/A", "nicotine": [0], "flavor": "Cristal de Murano Soplado", "battery": "N/A", "capacity": "Diámetro 15cm"}'::jsonb
);

-- 6. Crear tabla de categorías
CREATE TABLE IF NOT EXISTS public.categories (
    id TEXT PRIMARY KEY,
    name TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- 7. Habilitar Seguridad de Nivel de Fila (RLS) en categorías
ALTER TABLE public.categories ENABLE ROW LEVEL SECURITY;

-- 8. Crear Políticas de RLS para categorías
DROP POLICY IF EXISTS "Permitir lectura publica de categorias" ON public.categories;
CREATE POLICY "Permitir lectura publica de categorias" 
ON public.categories 
FOR SELECT 
USING (true);

DROP POLICY IF EXISTS "Permitir escrituras de categorias a usuarios autenticados" ON public.categories;
CREATE POLICY "Permitir escrituras de categorias a usuarios autenticados" 
ON public.categories 
FOR ALL 
TO authenticated
USING (true)
WITH CHECK (true);

-- 9. Insertar Categorías Iniciales (Semilla)
INSERT INTO public.categories (id, name)
VALUES 
('vapers', 'Vapers'),
('reposteria', 'Óxido Nitroso'),
('coleccionismo', 'Coleccionismo')
ON CONFLICT (id) DO NOTHING;

-- 10. Crear tabla de textos del sitio
CREATE TABLE IF NOT EXISTS public.site_texts (
    id TEXT PRIMARY KEY,
    es TEXT NOT NULL,
    en TEXT,
    zh TEXT,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- Habilitar RLS en site_texts
ALTER TABLE public.site_texts ENABLE ROW LEVEL SECURITY;

-- Políticas de RLS para site_texts
DROP POLICY IF EXISTS "Permitir lectura publica de textos" ON public.site_texts;
CREATE POLICY "Permitir lectura publica de textos" 
ON public.site_texts 
FOR SELECT 
USING (true);

DROP POLICY IF EXISTS "Permitir escrituras de textos a usuarios autenticados" ON public.site_texts;
CREATE POLICY "Permitir escrituras de textos a usuarios autenticados" 
ON public.site_texts 
FOR ALL 
TO authenticated
USING (true)
WITH CHECK (true);

-- Semilla de textos del Hero
INSERT INTO public.site_texts (id, es, en, zh) VALUES
('hero_b2b_tag', 'DISTRIBUIDORA MAYORISTA B2B', 'B2B WHOLESALE DISTRIBUTOR', 'B2B 批发分销商'),
('hero_title_part1', 'Importación Mayorista', 'Wholesale Import', '批发进口渠道'),
('hero_title_part2', 'Directo A Tu Negocio', 'Direct To Your Business', '直达您的店铺'),
('hero_desc', 'Distribución exclusiva de las marcas internacionales líderes para profesionales, autónomos y comercios. Vapeo homologado, óxido nitroso certificado para hostelería y coleccionables premium con pedidos directos vía WhatsApp.', 'Exclusive distribution of leading international brands for professionals, independent workers, and retailers. Certified vaping devices, hospitality-certified culinary nitrous oxide, and premium collectibles with direct WhatsApp ordering.', '为零售商、自由职业者及商店提供国际知名品牌的独家代理与分销。符合法规的电子烟、餐饮认证的一氧化二氮，以及限量级艺术收藏品，支持通过 WhatsApp 直接下单。'),
('hero_btn_catalog', 'Ver Catálogo B2B', 'View B2B Catalog', '浏览 B2B 目录'),
('hero_btn_guarantees', 'Garantías y Leyes', 'Guarantees & Laws', '合规与保证'),
('hero_usp1_title', 'Envío Directo', 'Direct Shipping', '本地直邮'),
('hero_usp1_desc', 'Express 24h a península', 'Express 24h to peninsula', '半岛地区 24 小时闪送'),
('hero_usp2_title', 'Calidad Importada', 'Imported Quality', '进口品质'),
('hero_usp2_desc', 'Homologado TPD y E942', 'TPD and E942 Approved', '符合 TPD 及 E942 认证'),
('hero_usp3_title', 'Catálogo Exclusivo', 'Exclusive Catalog', '独家选品'),
('hero_usp3_desc', 'Piezas y marcas de tendencia', 'Trend-setting parts and brands', '潮流新品与限量版珍品')
ON CONFLICT (id) DO UPDATE SET
  es = EXCLUDED.es,
  en = EXCLUDED.en,
  zh = EXCLUDED.zh;

-- Semilla de textos de la sección Proceso de Importación
INSERT INTO public.site_texts (id, es, en, zh) VALUES
('exp_tag', 'PROCESO DE IMPORTACIÓN', 'IMPORTATION PROCESS', '进口与通关流程'),
('exp_title_part1', 'Garantías de ', 'Guarantees of ', '我们的 '),
('exp_title_purple', 'VAPEX Import', 'VAPEX Import', 'VAPEX 进口保障'),
('exp_desc', 'Nos encargamos de todo el proceso de importación y aduanas para traer a España los artículos más exclusivos y de alta demanda del mercado internacional. Garantizamos la trazabilidad total y el cumplimiento legal de cada producto.', 'We manage the entire import and customs clearance process to bring Spain the most exclusive and highly demanded items from the international market. We guarantee full traceability and legal compliance for each product.', '我们全权负责所有进口、清关及商检手续，为西班牙市场引入最独特、高品质、高需求的国际热销商品。保障每一件商品的百分百可追溯性 y 合法合规。'),
('exp_bullet1_title', 'Regulación Europea TPD:', 'European TPD Regulation:', '欧盟 TPD 烟草指令合规：'),
('exp_bullet1_desc', ' Todos los vapers cumplen estrictamente con la directiva europea de tabaco y pureza.', ' All vapes comply strictly with the European tobacco directive and purity standards.', ' 所有电子烟产品均严格执行欧盟烟草指令与纯度标准。'),
('exp_bullet2_title', 'Pureza Certificada E942:', 'Certified Purity E942:', 'E942 食品级纯度认证：'),
('exp_bullet2_desc', ' Nuestro óxido nitroso culinario posee certificación de calidad alimentaria para cocina gourmet.', ' Our culinary nitrous oxide carries food-grade quality certification for gourmet kitchens.', ' 我们的美食一氧化二氮具备完整的食品级检测证书，可安全用于高端西点及创意分子料理。'),
('exp_bullet3_title', 'Coleccionables Verificados:', 'Verified Collectibles:', '官方原装收藏品认证：'),
('exp_bullet3_desc', ' Cada artículo de colección es de importación genuina y seleccionado por su estado premium.', ' Each collectible item is of genuine import origin and selected for its premium condition.', ' 每一件潮流收藏品均源自正规原产地进口，经过专家品质核验，保证完美成色。')
ON CONFLICT (id) DO UPDATE SET
  es = EXCLUDED.es,
  en = EXCLUDED.en,
  zh = EXCLUDED.zh;

-- Semilla de textos de la sección Sobre Nosotros
INSERT INTO public.site_texts (id, es, en, zh) VALUES
('about_title', 'Sobre VAPEX Import', 'About VAPEX Import', '关于 VAPEX Import'),
('about_desc', 'Somos una importadora especializada fundada en 2026 con la misión de facilitar el acceso a productos internacionales exclusivos de alta demanda. Gestionamos directamente el transporte y los despachos aduaneros para ofrecer a nuestros clientes en España vapers de gama alta, óxido nitroso certificado para repostería profesional y piezas limitadas de coleccionismo con entrega express desde nuestro almacén local.', 'We are a specialized importer founded in 2026 with the mission of facilitating access to exclusive, high-demand international products. We directly handle shipping and customs clearance to offer our clients in Spain high-end vapes, certified nitrous oxide for professional pastry, and limited pieces of collectibles with express delivery from our local warehouse.', '我们是一家成立于 2026 年的专业进口分销企业，致力于消除贸易壁垒，使高端国际独家商品变得触手可及。我们绕过层层中间商直接与原厂对接物流与清关，为西班牙本土商户提供高端电子烟、烘焙专用高纯气罐和限量版潮流艺术收藏品，并从本地仓库进行闪电式发货。'),
('about_stat1_num', '+10K', '+10K', '10K+'),
('about_stat1_desc', 'Clientes Satisfechos', 'Satisfied Clients', '商户满意信任'),
('about_stat2_num', '24H', '24H', '24小时'),
('about_stat2_desc', 'Envío Express', 'Express Shipping', '本土特快发货'),
('about_stat3_num', '100%', '100%', '100%'),
('about_stat3_desc', 'Original y Seguro', 'Original & Safe', '原装正品保障')
ON CONFLICT (id) DO UPDATE SET
  es = EXCLUDED.es,
  en = EXCLUDED.en,
  zh = EXCLUDED.zh;

-- Semilla de textos Legales y Advertencias
INSERT INTO public.site_texts (id, es, en, zh) VALUES
('footer_warning_b2b', 'ADVERTENCIA B2B: Portal exclusivo de venta mayorista para profesionales. De acuerdo con el R.D. Ley 17/2017 de España, los vapers con nicotina solo se distribuyen a establecimientos físicos autorizados y no a consumidores finales. El óxido nitroso se comercializa estrictamente para hostelería y repostería culinaria; su inhalación con otros fines es peligrosa y está prohibida.', 'B2B WARNING: Exclusive wholesale portal for professionals. Under Spanish R.D. Ley 17/2017, nicotine vapes are only distributed to authorized physical establishments and not to end consumers. Nitrous oxide is marketed strictly for hospitality and culinary pastry; inhalation for other purposes is dangerous and prohibited.', 'B2B 批发警示：本网站为仅限商户使用的批发门户。根据西班牙 R.D. Ley 17/2017，含尼古丁电子烟只能分销给授权实体零售点，禁止向最终消费者直销。一氧化二氮仅限餐饮烘焙专业用途使用，吸食吸入该气体具有极高危险性且属于违法行为。'),
('footer_brand_desc', 'Distribuidora e importadora mayorista online de vapeo premium, gases alimentarios y coleccionables.', 'Online wholesale distributor and importer of premium vaping, culinary gas, and limited collectibles.', '一站式高端电子烟、食品级特种气体及潮流限量艺术品大宗进口批发分销平台。'),
('alert_legal_notice', 'AVISO LEGAL:\nEste sitio web es operado por VAPEX Import S.L., con CIF B-12345678, domicilio social en Madrid, España. Portal de comercio electrónico exclusivo para profesionales (B2B).', 'LEGAL NOTICE:\nThis website is operated by VAPEX Import S.L., CIF B-12345678, registered address in Madrid, Spain. Exclusive e-commerce portal for professionals (B2B).', '法律声明：\n本网站由 VAPEX Import S.L. 运营。注册地址位于西班牙马德里，税号 CIF B-12345678。本网站属于专属 B2B 商户电子商务平台。'),
('alert_privacy_policy', 'POLÍTICA DE PRIVACIDAD:\nEn cumplimiento del RGPD, tus datos personales de contacto facilitados para la tramitación de pedidos a través de WhatsApp son procesados con la única finalidad de facturación y envío comercial.', 'PRIVACY POLICY:\nIn compliance with GDPR, your personal contact details provided for order processing through WhatsApp are processed solely for billing and commercial shipping purposes.', '隐私政策：\n根据 GDPR 规范，您为了通过 WhatsApp 进行订单结算而提交 de 商业联系数据，将仅用于发票开具及商业物流派送 de 目的进行处理。'),
('alert_cookies_policy', 'POLÍTICA DE COOKIES:\nEste sitio web utiliza almacenamiento técnico obligatorio (local storage) para gestionar tu verificación de edad y tu carrito de compras de forma anónima.', 'COOKIES POLICY:\nThis website uses required technical local storage to manage your age verification and your shopping cart anonymously.', 'Cookie 政策：\n本网站仅使用必要 de 技术型本地存储 (local storage) 以匿名方式管理您的年龄验证状态以及购物车内 de 商品。'),
('alert_b2b_terms', 'TÉRMINOS Y CONDICIONES B2B:\nTodas las ventas se gestionan mediante cierre comercial por WhatsApp. Se requiere acreditación fiscal (Modelo 036 o IAE) para validar transacciones mayoristas.', 'B2B TERMS AND CONDITIONS:\nAll sales are completed commercial closing via WhatsApp. Fiscal credentials (Model 036 or IAE) are required to validate wholesale transactions.', 'B2B 条款与条件：\n所有订单最终都通过 WhatsApp 确认闭环交易。商户须提供税务证明 (Modelo 036 或 IAE) 以验证大宗批发资质。')
ON CONFLICT (id) DO UPDATE SET
  es = EXCLUDED.es,
  en = EXCLUDED.en,
  zh = EXCLUDED.zh;


