-- ==========================================================================
-- SCRIPT DE CONFIGURACIÓN DE BASE DE DATOS PARA SUPABASE (VAPEX)
-- Ejecuta este script en el editor SQL de Supabase para crear las tablas
-- e insertar los productos iniciales.
-- ==========================================================================

-- 1. Crear tabla de productos
CREATE TABLE IF NOT EXISTS public.products (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    brand TEXT NOT NULL,
    category TEXT NOT NULL,
    price NUMERIC(10, 2) NOT NULL,
    rating NUMERIC(3, 1) NOT NULL DEFAULT 5.0,
    reviews INTEGER NOT NULL DEFAULT 0,
    image TEXT NOT NULL,
    in_stock BOOLEAN NOT NULL DEFAULT TRUE,
    stock_count INTEGER NOT NULL DEFAULT 10,
    description TEXT NOT NULL,
    details JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- 2. Habilitar Seguridad de Nivel de Fila (RLS)
ALTER TABLE public.products ENABLE ROW LEVEL SECURITY;

-- 3. Crear Políticas de RLS
-- Política 1: Permitir lectura pública a cualquiera (incluso no autenticados)
DROP POLICY IF EXISTS "Permitir lectura publica" ON public.products;
CREATE POLICY "Permitir lectura publica" 
ON public.products 
FOR SELECT 
USING (true);

-- Política 2: Permitir inserción, actualización y borrado solo a usuarios autenticados
DROP POLICY IF EXISTS "Permitir escrituras a usuarios autenticados" ON public.products;
CREATE POLICY "Permitir escrituras a usuarios autenticados" 
ON public.products 
FOR ALL 
TO authenticated
USING (true)
WITH CHECK (true);

-- 4. Truncar tabla de productos para asegurar semilla limpia
TRUNCATE TABLE public.products RESTART IDENTITY CASCADE;

-- 5. Insertar Datos de Ejemplo (Semilla)
INSERT INTO public.products (name, brand, category, price, rating, reviews, image, in_stock, stock_count, description, details)
VALUES 
(
  'Mango Peach Fusion Disposable', 
  'VAPEX Neon', 
  'vapers', 
  12.99, 
  4.8, 
  142, 
  '/images/vape_mango_peach.png', 
  TRUE, 
  15, 
  'Experimenta la explosión tropical definitiva con la fusión dulce de mangos maduros y melocotón jugoso. Este vape desechable ofrece caladas ultra suaves con un golpe de sabor consistente de principio a fin.',
  '{"puffs": "8000 Caladas", "nicotine": [0, 10, 20], "flavor": "Mango, Melocotón y Toque Ice", "battery": "650mAh (Recargable USB-C)", "capacity": "14ml"}'::jsonb
),
(
  'Pod Kit CyberBlue Pro', 
  'AeroPod', 
  'vapers', 
  29.99, 
  4.9, 
  88, 
  '/images/vape_pod_kit.png', 
  TRUE, 
  8, 
  'El Pod Kit definitivo para el día a día. Fabricado con aleación de aluminio aeroespacial y fibra de carbono. Cuenta con activación por calada o botón, control de flujo de aire ajustable y una pantalla inteligente OLED para el control de potencia.',
  '{"puffs": "N/A (Recargable)", "nicotine": [0, 10, 20, 50], "flavor": "Compatible con sales y e-liquids", "battery": "1000mAh (Carga Rápida USB-C)", "capacity": "2ml (Cartucho magnético)"}'::jsonb
),
(
  'Premium E-Liquid Fresa Limón', 
  'Juice Labs', 
  'vapers', 
  15.99, 
  4.7, 
  210, 
  '/images/vape_eliquid_bottle.png', 
  TRUE, 
  25, 
  'Una mezcla magistral de fresas dulces recién cosechadas equilibradas con un toque cítrico y refrescante de limón ácido. Ideal para vapear todo el día en atomizadores sub-ohm.',
  '{"puffs": "N/A", "nicotine": [0, 3, 6], "flavor": "Fresa Madura y Limonada Ácida", "battery": "N/A", "capacity": "60ml (70VG / 30PG)"}'::jsonb
),
(
  'Mod Box Cyberpunk Gold 200W', 
  'VoltTech', 
  'vapers', 
  64.99, 
  5.0, 
  45, 
  '/images/vape_mod_cyber.png', 
  TRUE, 
  4, 
  'Para los entusiastas del vapeo y el cloud chasing. Mod electrónico de doble batería 18650 con una potencia máxima de 200W. Diseño ergonómico de fibra de carbono con detalles chapados en oro y chipset de última generación con modos bypass y control de temperatura.',
  '{"puffs": "N/A", "nicotine": [0], "flavor": "N/A", "battery": "Doble Batería 18650 (No incluidas)", "capacity": "Rosca 510 universal"}'::jsonb
),
(
  'Cargadores de N2O Premium (50 uds)', 
  'CreamMaster Import', 
  'oxido-nitroso', 
  24.99, 
  4.8, 
  112, 
  '/images/n2o_charger.png', 
  TRUE, 
  30, 
  'Cargadores de óxido nitroso (N2O) de calidad culinaria para sifones de nata y espumas gourmet. Fabricados en acero reciclable de alta resistencia, garantizando la pureza del gas para repostería profesional sin residuos de aceite.',
  '{"puffs": "N/A", "nicotine": [0], "flavor": "Grado Alimentario Certificado E942", "battery": "N/A", "capacity": "50 cápsulas (8g N2O c/u)"}'::jsonb
),
(
  'Bombona de Óxido Nitroso N2O 640g', 
  'GourmetWhip', 
  'oxido-nitroso', 
  39.99, 
  4.9, 
  64, 
  '/images/n2o_charger.png', 
  TRUE, 
  12, 
  'Cilindro de gas óxido nitroso (N2O) de 640g de importación exclusiva para hostelería y repostería gourmet. Ahorra tiempo en recargas en comparación con los cargadores individuales. Compatible con la mayoría de sifones mediante regulador.',
  '{"puffs": "N/A", "nicotine": [0], "flavor": "Pureza 99.9% Alimentaria", "battery": "N/A", "capacity": "640g de gas neto"}'::jsonb
),
(
  'Encendedor Zippo Edición Dragón', 
  'Zippo Collectibles', 
  'coleccionismo', 
  89.99, 
  5.0, 
  28, 
  '/images/collectible_dragon.png', 
  TRUE, 
  5, 
  'Encendedor a prueba de viento de edición limitada, importado directamente desde USA. Acabado en latón cepillado de gran grosor con un intrincado grabado en relieve de un dragón oriental tradicional. Viene en estuche de regalo de lujo.',
  '{"puffs": "N/A", "nicotine": [0], "flavor": "Latón Cepillado Grabado", "battery": "Mecanismo de Piedra y Mecha", "capacity": "Estuche Oficial Incluido"}'::jsonb
),
(
  'Cenicero de Cristal de Murano Vintage', 
  'Murano Art', 
  'coleccionismo', 
  120.00, 
  4.7, 
  15, 
  '/images/vape_mod_cyber.png', 
  TRUE, 
  2, 
  'Pieza de colección vintage de los años 70, importada de Venecia, Italia. Cenicero soplado a mano en cristal de Murano con inclusiones de pan de oro y espirales de colores vibrantes. Un toque único y elegante de exclusividad.',
  '{"puffs": "N/A", "nicotine": [0], "flavor": "Cristal de Murano Soplado", "battery": "N/A", "capacity": "Diámetro 15cm"}'::jsonb
);
