-- ==========================================================================
-- SCRIPT DE CONFIGURACIÓN DE BASE DE DATOS PARA SUPABASE (VAPEX)
-- Ejecuta este script en el editor SQL de Supabase para crear las tablas
-- e insertar los productos iniciales.
-- ==========================================================================

-- 1. Crear tabla de productos
CREATE TABLE IF NOT EXISTS public.products (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    brand TEXT NOT NULL,
    category TEXT NOT NULL,
    price NUMERIC(10, 2) NOT NULL,
    rating NUMERIC(3, 1) NOT NULL DEFAULT 5.0,
    reviews INTEGER NOT NULL DEFAULT 0,
    image TEXT NOT NULL,
    in_stock BOOLEAN NOT NULL DEFAULT TRUE,
    stock_count INTEGER NOT NULL DEFAULT 10,
    description TEXT NOT NULL,
    details JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- 2. Habilitar Seguridad de Nivel de Fila (RLS)
ALTER TABLE public.products ENABLE ROW LEVEL SECURITY;

-- 3. Crear Políticas de RLS
-- Política 1: Permitir lectura pública a cualquiera (incluso no autenticados)
CREATE POLICY "Permitir lectura publica" 
ON public.products 
FOR SELECT 
USING (true);

-- Política 2: Permitir inserción, actualización y borrado solo a usuarios autenticados
CREATE POLICY "Permitir escrituras a usuarios autenticados" 
ON public.products 
FOR ALL 
TO authenticated
USING (true)
WITH CHECK (true);

-- 4. Insertar Datos de Ejemplo (Semilla)
INSERT INTO public.products (name, brand, category, price, rating, reviews, image, in_stock, stock_count, description, details)
VALUES 
(
  'Mango Peach Fusion Disposable', 
  'VAPEX Neon', 
  'desechables', 
  12.99, 
  4.8, 
  142, 
  '/images/vape_mango_peach.png', 
  TRUE, 
  15, 
  'Experimenta la explosión tropical definitiva con la fusión dulce de mangos maduros y melocotón jugoso. Este vape desechable ofrece caladas ultra suaves con un golpe de sabor consistente de principio a fin.',
  '{"puffs": "8000 Caladas", "nicotine": [0, 10, 20], "flavor": "Mango, Melocotón y Toque Ice", "battery": "650mAh (Recargable USB-C)", "capacity": "14ml"}'::jsonb
),
(
  'Pod Kit CyberBlue Pro', 
  'AeroPod', 
  'pods', 
  29.99, 
  4.9, 
  88, 
  '/images/vape_pod_kit.png', 
  TRUE, 
  8, 
  'El Pod Kit definitivo para el día a día. Fabricado con aleación de aluminio aeroespacial y fibra de carbono. Cuenta con activación por calada o botón, control de flujo de aire ajustable y una pantalla inteligente OLED para el control de potencia.',
  '{"puffs": "N/A (Recargable)", "nicotine": [0, 10, 20, 50], "flavor": "Compatible con sales y e-liquids", "battery": "1000mAh (Carga Rápida USB-C)", "capacity": "2ml (Cartucho magnético)"}'::jsonb
),
(
  'Premium E-Liquid Fresa Limón', 
  'Juice Labs', 
  'eliquids', 
  15.99, 
  4.7, 
  210, 
  '/images/vape_eliquid_bottle.png', 
  TRUE, 
  25, 
  'Una mezcla magistral de fresas dulces recién cosechadas equilibradas con un toque cítrico y refrescante de limón ácido. Ideal para vapear todo el día en atomizadores sub-ohm.',
  '{"puffs": "N/A", "nicotine": [0, 3, 6], "flavor": "Fresa Madura y Limonada Ácida", "battery": "N/A", "capacity": "60ml (70VG / 30PG)"}'::jsonb
),
(
  'Mod Box Cyberpunk Gold 200W', 
  'VoltTech', 
  'mods', 
  64.99, 
  5.0, 
  45, 
  '/images/vape_mod_cyber.png', 
  TRUE, 
  4, 
  'Para los entusiastas del vapeo y el cloud chasing. Mod electrónico de doble batería 18650 con una potencia máxima de 200W. Diseño ergonómico de fibra de carbono con detalles chapados en oro y chipset de última generación con modos bypass y control de temperatura.',
  '{"puffs": "N/A", "nicotine": [0], "flavor": "N/A", "battery": "Doble Batería 18650 (No incluidas)", "capacity": "Rosca 510 universal"}'::jsonb
),
(
  'Blueberry Sour Raspberry Ice', 
  'VAPEX Neon', 
  'desechables', 
  11.99, 
  4.6, 
  95, 
  '/images/vape_blueberry.png', 
  TRUE, 
  12, 
  'Un balance perfecto entre el dulzor de los arándanos silvestres y la acidez de las frambuesas azules, finalizado con una ráfaga helada de mentol. Práctico, compacto y lleno de sabor.',
  '{"puffs": "7000 Caladas", "nicotine": [10, 20], "flavor": "Arándanos, Frambuesa Ácida e Ice", "battery": "600mAh (Recargable USB-C)", "capacity": "12ml"}'::jsonb
),
(
  'Menthol Frost E-Liquid', 
  'Juice Labs', 
  'eliquids', 
  14.99, 
  4.8, 
  130, 
  '/images/vape_mint_bottle.png', 
  FALSE, 
  0, 
  'Una experiencia intensamente fresca. Mentol glacial puro combinado con notas sutiles de menta verde para una sensación refrescante insuperable en la garganta. Perfecto solo o para mezclar con tus sabores favoritos.',
  '{"puffs": "N/A", "nicotine": [0, 3, 6, 12], "flavor": "Mentol Extra Fuerte y Menta", "battery": "N/A", "capacity": "60ml (50VG / 50PG)"}'::jsonb
)
ON CONFLICT DO NOTHING;
